### ISSUE TITLE
Deploy DMN decision together with BPMN file

### ISSUE THREAD

**Issue by epalmen** [camunda-community-hub/camunda-platform-8-github-action#34]
Hi,
Iam using the workflow for my projects which is great.
But I have a flow that uses DMN decision tables and they get not deployed. 
What am I doing wrong or is this functionality not realized yet,

regards,
Erik

**Comment by jwulf** [comment]
DMN decision tables are not supported yet. Let me take a look at it.

**Comment by jwulf** [comment]
OK, I created an 8.3.0 tag that supports it, and master will now support it as well. 

Please let me know if you run into any issues. Thanks for using the GitHub Action!
